## Preprocessing

In [81]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [82]:
# Drop the non-beneficial ID columns
drop_columns = ['EIN']
application_df = application_df.drop(columns = drop_columns)

In [83]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [84]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [85]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [86]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_count = 200
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_counts[application_counts < cutoff_count].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [87]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [88]:
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Filter types with counts greater than the cutoff
counts = classification_counts[classification_counts > 1]
counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [89]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_count = 50
classification_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = classification_counts[classification_counts < cutoff_count].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: CLASSIFICATION, dtype: int64

In [90]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [51]:
# Look at NAME value counts for binning
# application_df['NAME'].value_counts()

In [91]:
# Choose a cutoff value and create a list of names to be replaced

cutoff_count = 50
name_counts = application_df['NAME'].value_counts()
names_to_replace = name_counts[name_counts < cutoff_count].index

# Replace in dataframe
for cls in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: NAME, dtype: int64

In [12]:
# Look at ASK_AMT value counts for binning
# application_df['ASK_AMT'].value_counts()

5000        25398
10478           3
15583           3
63981           3
6725            3
            ...
5371754         1
30060           1
43091152        1
18683           1
36500179        1
Name: ASK_AMT, Length: 8747, dtype: int64

In [51]:
# Determine the number of bins
# num_bins = 50

# Create bins for the ASK_AMT feature
# application_df['ASK_AMT_Binned'] = pd.cut(application_df['ASK_AMT'], bins=num_bins, labels=False)


# application_df['ASK_AMT_Binned'].value_counts()

0     34219
1        33
5        10
2         9
3         6
4         5
8         3
13        2
49        2
6         2
7         2
27        1
19        1
11        1
10        1
9         1
32        1
Name: ASK_AMT_Binned, dtype: int64

In [53]:
# application_df.drop(columns=['ASK_AMT'], inplace=True)

In [92]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [93]:

# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

# drop 'IS SUCCESSFUL'
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0859000e+05, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.6500179e+07, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

In [94]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [95]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [96]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=10
hidden_nodes_layer2=20
hidden_nodes_layer3=30
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_19 (Dense)            (None, 10)                1060

 dense_20 (Dense)            (None, 20)                220

 dense_21 (Dense)            (None, 20)                420

 dense_22 (Dense)            (None, 1)                 21

=================================================================
Total params: 1721 (6.72 KB)
Trainable params: 1721 (6.72 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [97]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [98]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 3ms/step - loss: 0.5378 - accuracy: 0.7271 - val_loss: 0.4768 - val_accuracy: 0.7701
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4860 - accuracy: 0.7609 - val_loss: 0.4688 - val_accuracy: 0.7691
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4807 - accuracy: 0.7629 - val_loss: 0.4690 - val_accuracy: 0.7756
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4784 - accuracy: 0.7649 - val_loss: 0.4663 - val_accuracy: 0.7753
Epoch 5/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4773 - accuracy: 0.7653 - val_loss: 0.4659 - val_accuracy: 0.7733
Epoch 6/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7647 - val_loss: 0.4677 - val_accuracy: 0.7727
Epoch 7/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4752 - accuracy: 0.7656 - val_loss: 0.4668 - val_accuracy: 0.7751
Epoch 8/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4738 - accuracy: 0.7667 - val_loss: 0.4649 - val_accuracy: 0.7761
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4741 - accuracy: 0.7657 - val_loss: 0.4645 - val_accuracy: 0.7771
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4729 - accuracy: 0.7679 - val_loss: 0.4663 - val_accuracy: 0.7766
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4723 - accuracy: 0.7680 - val_loss: 0.4643 - val_accuracy: 0.7753
Epoch 12/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7694 - val_loss: 0.4680 - val_accuracy: 0.7756
Epoch 13/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7683 - val_loss: 0.4671 - val_accuracy: 0.7730
Epoch 14/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7682 - val_loss: 0.4643 - val_accuracy: 0.7761
Epoch 15/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4700 - accuracy: 0.7689 - val_loss: 0.4661 - val_accuracy: 0.7766
Epoch 16/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4694 - accuracy: 0.7688 - val_loss: 0.4659 - val_accuracy: 0.7771
Epoch 17/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4691 - accuracy: 0.7701 - val_loss: 0.4658 - val_accuracy: 0.7748
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4687 - accuracy: 0.7705 - val_loss: 0.4662 - val_accuracy: 0.7756
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4681 - accuracy: 0.7704 - val_loss: 0.4650 - val_accuracy: 0.7779
Epoch 20/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4682 - accuracy: 0.7704 - val_loss: 0.4661 - val_accuracy: 0.7769
Epoch 21/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4681 - accuracy: 0.7704 - val_loss: 0.4657 - val_accuracy: 0.7761
Epoch 22/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4676 - accuracy: 0.7712 - val_loss: 0.4663 - val_accuracy: 0.7782
Epoch 23/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4675 - accuracy: 0.7705 - val_loss: 0.4666 - val_accuracy: 0.7790
Epoch 24/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4676 - accuracy: 0.7705 - val_loss: 0.4658 - val_accuracy: 0.7746
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4667 - accuracy: 0.7714 - val_loss: 0.4679 - val_accuracy: 0.7751
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4669 - accuracy: 0.7714 - val_loss: 0.4661 - val_accuracy: 0.7790
Epoch 27/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4667 - accuracy: 0.7715 - val_loss: 0.4660 - val_accuracy: 0.7740
Epoch 28/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4663 - accuracy: 0.7707 - val_loss: 0.4667 - val_accuracy: 0.7761
Epoch 29/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4666 - accuracy: 0.7714 - val_loss: 0.4651 - val_accuracy: 0.7756
Epoch 30/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4662 - accuracy: 0.7728 - val_loss: 0.4667 - val_accuracy: 0.7761
Epoch 31/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4659 - accuracy: 0.7722 - val_loss: 0.4675 - val_accuracy: 0.7753
Epoch 32/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4656 - accuracy: 0.7724 - val_loss: 0.4668 - val_accuracy: 0.7748
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4654 - accuracy: 0.7728 - val_loss: 0.4679 - val_accuracy: 0.7758
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4652 - accuracy: 0.7732 - val_loss: 0.4655 - val_accuracy: 0.7766
Epoch 35/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4650 - accuracy: 0.7726 - val_loss: 0.4650 - val_accuracy: 0.7733
Epoch 36/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4649 - accuracy: 0.7738 - val_loss: 0.4658 - val_accuracy: 0.7751
Epoch 37/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4647 - accuracy: 0.7732 - val_loss: 0.4664 - val_accuracy: 0.7758
Epoch 38/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4646 - accuracy: 0.7730 - val_loss: 0.4662 - val_accuracy: 0.7787
Epoch 39/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4643 - accuracy: 0.7736 - val_loss: 0.4663 - val_accuracy: 0.7787
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4645 - accuracy: 0.7746 - val_loss: 0.4693 - val_accuracy: 0.7777
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4645 - accuracy: 0.7734 - val_loss: 0.4691 - val_accuracy: 0.7764
Epoch 42/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4644 - accuracy: 0.7738 - val_loss: 0.4675 - val_accuracy: 0.7753
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4638 - accuracy: 0.7735 - val_loss: 0.4676 - val_accuracy: 0.7766
Epoch 44/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4640 - accuracy: 0.7741 - val_loss: 0.4658 - val_accuracy: 0.7771
Epoch 45/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4635 - accuracy: 0.7744 - val_loss: 0.4665 - val_accuracy: 0.7769
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4635 - accuracy: 0.7738 - val_loss: 0.4673 - val_accuracy: 0.7777
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4636 - accuracy: 0.7734 - val_loss: 0.4656 - val_accuracy: 0.7756
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4631 - accuracy: 0.7745 - val_loss: 0.4676 - val_accuracy: 0.7777
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4632 - accuracy: 0.7743 - val_loss: 0.4686 - val_accuracy: 0.7777
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4627 - accuracy: 0.7735 - val_loss: 0.4705 - val_accuracy: 0.7764
Epoch 51/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4631 - accuracy: 0.7745 - val_loss: 0.4667 - val_accuracy: 0.7774
Epoch 52/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4627 - accuracy: 0.7750 - val_loss: 0.4661 - val_accuracy: 0.7758
Epoch 53/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4627 - accuracy: 0.7743 - val_loss: 0.4680 - val_accuracy: 0.7753
Epoch 54/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4629 - accuracy: 0.7735 - val_loss: 0.4663 - val_accuracy: 0.7764
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4627 - accuracy: 0.7753 - val_loss: 0.4687 - val_accuracy: 0.7769
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4627 - accuracy: 0.7739 - val_loss: 0.4664 - val_accuracy: 0.7782
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4627 - accuracy: 0.7745 - val_loss: 0.4678 - val_accuracy: 0.7769
Epoch 58/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4619 - accuracy: 0.7750 - val_loss: 0.4664 - val_accuracy: 0.7761
Epoch 59/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4622 - accuracy: 0.7742 - val_loss: 0.4665 - val_accuracy: 0.7787
Epoch 60/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4620 - accuracy: 0.7752 - val_loss: 0.4674 - val_accuracy: 0.7743
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4624 - accuracy: 0.7745 - val_loss: 0.4676 - val_accuracy: 0.7751
Epoch 62/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4611 - accuracy: 0.7749 - val_loss: 0.4690 - val_accuracy: 0.7771
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4618 - accuracy: 0.7740 - val_loss: 0.4688 - val_accuracy: 0.7740
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4616 - accuracy: 0.7744 - val_loss: 0.4670 - val_accuracy: 0.7761
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4619 - accuracy: 0.7751 - val_loss: 0.4677 - val_accuracy: 0.7756
Epoch 66/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4616 - accuracy: 0.7751 - val_loss: 0.4683 - val_accuracy: 0.7764
Epoch 67/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4614 - accuracy: 0.7752 - val_loss: 0.4685 - val_accuracy: 0.7735
Epoch 68/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4611 - accuracy: 0.7745 - val_loss: 0.4687 - val_accuracy: 0.7766
Epoch 69/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4615 - accuracy: 0.7754 - val_loss: 0.4691 - val_accuracy: 0.7727
Epoch 70/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4615 - accuracy: 0.7748 - val_loss: 0.4671 - val_accuracy: 0.7779
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4611 - accuracy: 0.7748 - val_loss: 0.4656 - val_accuracy: 0.7761
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4611 - accuracy: 0.7746 - val_loss: 0.4685 - val_accuracy: 0.7777
Epoch 73/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4616 - accuracy: 0.7753 - val_loss: 0.4669 - val_accuracy: 0.7795
Epoch 74/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4608 - accuracy: 0.7742 - val_loss: 0.4658 - val_accuracy: 0.7758
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4611 - accuracy: 0.7737 - val_loss: 0.4669 - val_accuracy: 0.7753
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4607 - accuracy: 0.7754 - val_loss: 0.4679 - val_accuracy: 0.7758
Epoch 77/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4608 - accuracy: 0.7747 - val_loss: 0.4683 - val_accuracy: 0.7758
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4605 - accuracy: 0.7749 - val_loss: 0.4661 - val_accuracy: 0.7761
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4603 - accuracy: 0.7746 - val_loss: 0.4683 - val_accuracy: 0.7774
Epoch 80/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4602 - accuracy: 0.7751 - val_loss: 0.4692 - val_accuracy: 0.7766
Epoch 81/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4605 - accuracy: 0.7748 - val_loss: 0.4678 - val_accuracy: 0.7753
Epoch 82/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4599 - accuracy: 0.7758 - val_loss: 0.4666 - val_accuracy: 0.7746
Epoch 83/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4600 - accuracy: 0.7752 - val_loss: 0.4694 - val_accuracy: 0.7769
Epoch 84/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4598 - accuracy: 0.7756 - val_loss: 0.4687 - val_accuracy: 0.7779
Epoch 85/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4600 - accuracy: 0.7751 - val_loss: 0.4697 - val_accuracy: 0.7779
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4603 - accuracy: 0.7759 - val_loss: 0.4718 - val_accuracy: 0.7746
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4600 - accuracy: 0.7753 - val_loss: 0.4674 - val_accuracy: 0.7779
Epoch 88/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4599 - accuracy: 0.7757 - val_loss: 0.4675 - val_accuracy: 0.7777
Epoch 89/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4595 - accuracy: 0.7761 - val_loss: 0.4673 - val_accuracy: 0.7748
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4598 - accuracy: 0.7751 - val_loss: 0.4672 - val_accuracy: 0.7746
Epoch 91/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4601 - accuracy: 0.7753 - val_loss: 0.4659 - val_accuracy: 0.7774
Epoch 92/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4598 - accuracy: 0.7756 - val_loss: 0.4688 - val_accuracy: 0.7761
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4594 - accuracy: 0.7754 - val_loss: 0.4672 - val_accuracy: 0.7764
Epoch 94/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4594 - accuracy: 0.7746 - val_loss: 0.4695 - val_accuracy: 0.7746
Epoch 95/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4595 - accuracy: 0.7758 - val_loss: 0.4704 - val_accuracy: 0.7751
Epoch 96/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4598 - accuracy: 0.7755 - val_loss: 0.4681 - val_accuracy: 0.7758
Epoch 97/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4593 - accuracy: 0.7752 - val_loss: 0.4697 - val_accuracy: 0.7740
Epoch 98/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4596 - accuracy: 0.7756 - val_loss: 0.4699 - val_accuracy: 0.7756
Epoch 99/100
684/684 [==============================] - 2s 2ms/step - loss: 0.4589 - accuracy: 0.7761 - val_loss: 0.4664 - val_accuracy: 0.7733
Epoch 100/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4595 - accuracy: 0.7751 - val_loss: 0.4688 - val_accuracy: 0.7782

In [99]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4898 - accuracy: 0.7623 - 398ms/epoch - 1ms/step
Loss: 0.4897964298725128, Accuracy: 0.7623323798179626

In [100]:
# Export model to HDF5 File

from google.colab import files

nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(